# automatically generated by the FlatBuffers compiler, do not modify

# module: Example2

import FlatBuffers

mutable struct Monster
end
FlatBuffers.@ALIGN(Monster, 1)

function Monster(buf::Vector{UInt8}, offset::Integer)
    FlatBuffers.read(Monster, buf, offset)
end

