# automatically generated by the FlatBuffers compiler, do not modify

# module: Example2

import FlatBuffers

mutable struct Monster
end
FlatBuffers.@ALIGN(Monster, 1)

function Monster(buf::AbstractVector{UInt8}, pos::Integer)
    FlatBuffers.read(Monster, buf, pos)
end

