# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

@FlatBuffers.STRUCT struct Ability
    id::UInt32
    distance::UInt32
end
FlatBuffers.@ALIGN(Ability, 4)
FlatBuffers.offsets(::Type{T}) where {T<:Ability} = [0, 4]

function Ability(buf::Vector{UInt8}, offset::Integer)
    FlatBuffers.read(Ability, buf, offset)
end

