# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

@FlatBuffers.STRUCT struct Ability
    id::UInt32
    distance::UInt32
end
FlatBuffers.@ALIGN(Ability, 4)

function Ability(buf::AbstractVector{UInt8}, pos::Integer)
    FlatBuffers.read(Ability, buf, pos)
end

