# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

module Example
    include("Color.jl")
    include("Test.jl")
    include("Vec3.jl")
    include("Stat.jl")
    include("Ability.jl")
    include("Referrable.jl")
    include("Monster.jl")
    include("TestSimpleTableWithEnum.jl")
    include("Any_.jl")
    include("TypeAliases.jl")
end
