# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

FlatBuffers.@with_kw mutable struct Referrable
    id::UInt64 = 0
end
FlatBuffers.@ALIGN(Referrable, 1)
FlatBuffers.offsets(::Type{T}) where {T<:Referrable} = [
    0x00000004
]

function Referrable(buf::AbstractVector{UInt8}, pos::Integer)
    FlatBuffers.read(Referrable, buf, pos)
end

