# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

FlatBuffers.@with_kw mutable struct Referrable
    id::UInt64 = 0
end
FlatBuffers.@ALIGN(Referrable, 1)
FlatBuffers.offsets(::Type{T}) where {T<:Referrable} = [4]

function Referrable(buf::Vector{UInt8}, offset::Integer)
    FlatBuffers.read(Referrable, buf, offset)
end

