# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

FlatBuffers.@with_kw mutable struct Stat
    id::String = ""
    val::Int64 = 0
    count::UInt16 = 0
end
FlatBuffers.@ALIGN(Stat, 1)
FlatBuffers.offsets(::Type{T}) where {T<:Stat} = [4, 6, 8]

function Stat(buf::Vector{UInt8}, offset::Integer)
    FlatBuffers.read(Stat, buf, offset)
end

