# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

FlatBuffers.@with_kw mutable struct Stat
    id::String = ""
    val::Int64 = 0
    count::UInt16 = 0
end
FlatBuffers.@ALIGN(Stat, 1)
FlatBuffers.offsets(::Type{T}) where {T<:Stat} = [
    0x00000004, 0x00000006, 0x00000008
]

function Stat(buf::AbstractVector{UInt8}, pos::Integer)
    FlatBuffers.read(Stat, buf, pos)
end

