# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

@FlatBuffers.STRUCT struct Test
    a::Int16
    b::Int8
end
FlatBuffers.@ALIGN(Test, 2)
FlatBuffers.offsets(::Type{T}) where {T<:Test} = [0, 2]

function Test(buf::Vector{UInt8}, offset::Integer)
    FlatBuffers.read(Test, buf, offset)
end

