# automatically generated by the FlatBuffers compiler, do not modify

# module: Example

import FlatBuffers

FlatBuffers.@with_kw mutable struct TestSimpleTableWithEnum
    color::Int8 = 2
end
FlatBuffers.@ALIGN(TestSimpleTableWithEnum, 1)
FlatBuffers.offsets(::Type{T}) where {T<:TestSimpleTableWithEnum} = [4]

function TestSimpleTableWithEnum(buf::Vector{UInt8}, offset::Integer)
    FlatBuffers.read(TestSimpleTableWithEnum, buf, offset)
end

