# automatically generated by the FlatBuffers compiler, do not modify

# module: MyGame

import FlatBuffers

mutable struct InParentNamespace
end
FlatBuffers.@ALIGN(InParentNamespace, 1)

function InParentNamespace(buf::Vector{UInt8}, offset::Integer)
    FlatBuffers.read(InParentNamespace, buf, offset)
end

