# automatically generated by the FlatBuffers compiler, do not modify

# module: MyGame

import FlatBuffers

mutable struct InParentNamespace
end
FlatBuffers.@ALIGN(InParentNamespace, 1)

InParentNamespace(buf::AbstractVector{UInt8}, pos::Integer=0) = FlatBuffers.read(InParentNamespace, buf, pos)
InParentNamespace(io::IO) = FlatBuffers.deserialize(io, InParentNamespace)
